import Head from 'next/head'
import style from '@/styles/index.module.css'
import { useState, useEffect } from 'react'
import cookies from 'js-cookie';

export default function Home() {
  const [text, setText] = useState('');
  const [name, setName] = useState('');
  const [messages, SetMessages] = useState([]);
  const [newMessages,setNewMessages] = useState([]);

  useEffect(() => {
    const setNew = () => {
      SetMessages([...messages, ...newMessages]);
    }
    setNew();
  }, [newMessages])

  useEffect(() => {
    
  }, [])

  useEffect(() => {
    let oldLength;
    let oldData;
    const getMessages = async () => {
      const response = await fetch('/api/getAllMessages')
      const data = await response.json();
      oldLength = data.data.length;
      oldData = data.data;
      SetMessages(data.data);
    }

    const interval = setInterval(async () => {
      const response = await fetch('/api/getLength')
      const data = await response.json();
      const length = data.length;
      console.log(length === oldLength);
      if (length !== oldLength) {
        const response = await fetch('/api/getMessage', {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({
            messages: oldData,
          })
        })
        const data = await response.json();
        setNewMessages(data.messages);
        oldLength = length;
        oldData.push(data.messages)
      }
    }, 2500);

    getMessages();

    const getName = async () => {
      const response = await fetch('https://randomuser.me/api/', {
        headers: {
          'Content-Type': 'application/json',
        }
      });
      const data = await response.json();
      setName(data.results[0].name.first);
      cookies.set('_n', data.results[0].name.first);
    }
    if (cookies.get('_n')) setName(cookies.get('_n')); 
    else getName()

    return () => {
      clearInterval(interval);
    };
  }, []) 

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (text.trim() === '') return;
    setText('');
    console.log('click');
    const response = await fetch('/api/sendMessage', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({
        name: name,
        text: text,
      })
    })
  }

  return (
    <>
      <Head>
        <title>aMessage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <span className={style.your_name}>Your name is {name}</span>
        <div className={style.messages_area}>
          <div className={style.input_area}>
            <form onSubmit={handleSubmit}>
              <input value = {text} onChange = {(e) => {setText(e.target.value)}} maxLength={115}/>
              <button type = 'submit'>{'>'}</button>
            </form>
          </div>
          <ul>
          {messages.sort((a,b) => {return b.id - a.id}).map(({id,text,name, date}, index)=> {
            const newdate = new Date(date);
            const correctDate = newdate.getDate() + '/' + (newdate.getMonth() + 1) + ' ' + newdate.getHours() + ':' + newdate.getMinutes();
            return <li key = {index}>
              {correctDate} · {name}: {text}
             </li>
            })}
          </ul>
        </div>
      </main>
    </>
  )
}
